# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local nodeâ€™s name is included in this list
configuration:
    - name: alice
      ip: 127.0.0.1
      port: 4000 # This is the incoming port on which MP will listen
# May be changed for further communication as usual
    - name: bob
      ip: 127.0.0.1
      port: 14255
    - name: charlie
      ip: 127.0.0.1
      port: 12998
    - name: daphnie
      ip: 127.0.0.1
      port: 1987
sendRules:
    - action: drop # Ack message number 4 from bob to alice will not be sent
      src: bob
      dest: alice
      kind: Ack
      #seqNum: 4
    - action: delay # Every Lookup message in the system will be delayed
      kind: Lookup
    - action: duplicate # Every Lookup message in the system will be delayed
      kind: rec_dup
receiveRules:
    - action: duplicate # 3rd message from Charlie that anyone
      src: Charlie # receives will be duplicated
      seqNum: 3
    - action: drop
      kind: rec_drop
    - action: delay
      kind: rec_delay
# - action: drop
#      duplicate: true
    - action: duplicate
      kind: rec_dup
